/**
 * @file logger.hpp
 * @brief Levelled logging for HydroGrav.
 *
 * HydroGrav reports progress, warnings and diagnostics through the macros
 * declared here rather than writing to @c std::cout directly, so that an
 * embedding application can silence the library or capture its output.
 * 
 * THIS FILE WAS GENERATED BY CLAUDE OPUS 5.0.
 *
 * Two controls are provided:
 *
 * - @c logging::set_level() sets the severity threshold. Records below it are
 *   neither formatted nor emitted, so the streamed arguments are never
 *   evaluated.
 * - @c logging::set_sink() replaces the destination. The default sink writes
 *   @c Warn and @c Error to @c std::cerr and everything else to @c std::cout,
 *   which reproduces the behaviour of earlier versions.
 *
 * A host application with its own logging framework installs a sink:
 *
 * @code
 * logging::set_sink([](logging::Level level, const std::string& msg) {
 *     my_logger(to_my_severity(level)) << msg;
 * });
 * @endcode
 *
 * Emitting a record is thread safe; the sink is invoked under a lock, so
 * records written from OpenMP worker threads cannot interleave.
 */
#ifndef INCLUDE_LOGGER_HPP_H
#define INCLUDE_LOGGER_HPP_H

#include <atomic>
#include <functional>
#include <iostream>
#include <mutex>
#include <sstream>
#include <string>
#include <utility>

/**
 * @namespace logging
 * @brief Severity-filtered logging facility.
 */
namespace logging {

/**
 * @brief Severity of a log record, in increasing order.
 *
 * @c Off is not a severity a record can carry; it is only meaningful as a
 * threshold, where it silences the library completely.
 */
enum class Level {
    Trace,  ///< Per-iteration solver detail. Very verbose.
    Debug,  ///< Developer diagnostics and timings.
    Info,   ///< Progress messages and file input/output.
    Warn,   ///< Recoverable problems, typically a fallback being used.
    Error,  ///< Failures that prevent a result from being produced.
    Off     ///< Threshold only: emit nothing.
};

/** @brief Name of a severity, as used by the default sink. */
inline const char* to_string(Level level) {
    switch (level) {
        case Level::Trace: return "trace";
        case Level::Debug: return "debug";
        case Level::Info:  return "info";
        case Level::Warn:  return "warning";
        case Level::Error: return "error";
        case Level::Off:   return "off";
    }
    return "unknown";
}

/**
 * @brief Drop one trailing newline, if present.
 *
 * A record carries no trailing newline - the sink decides how to terminate it -
 * so text built with a stream block that ends in "\\n" is trimmed before it is
 * logged.
 */
inline std::string trim_trailing_newline(std::string text) {
    if (!text.empty() && text.back() == '\n') {
        text.pop_back();
    }
    return text;
}

/**
 * @brief Destination for emitted records.
 *
 * The string holds the whole record and carries no trailing newline; a sink
 * that writes to a stream is responsible for line termination.
 */
using Sink = std::function<void(Level, const std::string&)>;

namespace detail {

/// The active threshold. Atomic so that it can be read from worker threads.
inline std::atomic<Level>& level_storage() {
    static std::atomic<Level> level{Level::Info};
    return level;
}

/// Serialises sink invocation so that concurrent records cannot interleave.
inline std::mutex& sink_mutex() {
    static std::mutex m;
    return m;
}

/**
 * @brief Writes Warn and Error to cerr and everything else to cout.
 *
 * Warnings and errors are prefixed, since with a plain sink the severity is
 * otherwise not visible in the output.
 */
inline void default_sink(Level level, const std::string& msg) {
    switch (level) {
        case Level::Error:
            std::cerr << "Error: " << msg << "\n";
            break;
        case Level::Warn:
            std::cerr << "Warning: " << msg << "\n";
            break;
        default:
            std::cout << msg << "\n";
            break;
    }
}

inline Sink& sink_storage() {
    static Sink sink = &default_sink;
    return sink;
}

} // namespace detail

/** @brief Set the severity threshold. Records below @p level are discarded. */
inline void set_level(Level level) {
    detail::level_storage().store(level, std::memory_order_relaxed);
}

/** @brief Current severity threshold. */
inline Level get_level() {
    return detail::level_storage().load(std::memory_order_relaxed);
}

/**
 * @brief Whether a record of severity @p level would be emitted.
 *
 * A threshold of @c Off silences everything, since no record carries a
 * severity that high.
 */
inline bool enabled(Level level) {
    return level >= get_level();
}

/**
 * @brief Install a destination for log records.
 *
 * Passing an empty function restores the default sink.
 */
inline void set_sink(Sink sink) {
    std::lock_guard<std::mutex> lock(detail::sink_mutex());
    detail::sink_storage() = sink ? std::move(sink) : Sink(&detail::default_sink);
}

/**
 * @brief Temporarily change the severity threshold.
 *
 * Restores the previous threshold when it goes out of scope, including when
 * the scope is left by an exception.
 */
class ScopedLevel {
  public:
    explicit ScopedLevel(Level level) : previous_(get_level()) { set_level(level); }
    ~ScopedLevel() { set_level(previous_); }

    ScopedLevel(const ScopedLevel&) = delete;
    ScopedLevel& operator=(const ScopedLevel&) = delete;

  private:
    Level previous_;
};

/**
 * @brief Temporarily ensure records of severity @p level are emitted.
 *
 * Lowers the threshold to @p level if it is currently higher, and leaves it
 * alone otherwise, so it never makes the library quieter than the caller asked
 * for. Restores the previous threshold on scope exit.
 *
 * This exists to implement the deprecated @c dev logging flags in terms of the
 * severity threshold. Like those flags it changes global state, so it is only
 * appropriate on a serial code path.
 */
class ScopedVerbosity {
  public:
    explicit ScopedVerbosity(Level level) : previous_(get_level()) {
        if (previous_ > level) {
            set_level(level);
        }
    }
    ~ScopedVerbosity() { set_level(previous_); }

    ScopedVerbosity(const ScopedVerbosity&) = delete;
    ScopedVerbosity& operator=(const ScopedVerbosity&) = delete;

  private:
    Level previous_;
};

/**
 * @class Record
 * @brief One log record, emitted to the sink when it goes out of scope.
 *
 * Constructed by the @c HG_LOG macro; there is no reason to use it directly.
 */
class Record {
  public:
    explicit Record(Level level) : level_(level) {}

    ~Record() {
        // A sink must not throw from a destructor's call stack; swallow anything
        // it raises rather than terminating the program mid-calculation.
        try {
            std::lock_guard<std::mutex> lock(detail::sink_mutex());
            const Sink& sink = detail::sink_storage();
            if (sink) {
                sink(level_, buffer_.str());
            }
        } catch (...) {
        }
    }

    Record(const Record&) = delete;
    Record& operator=(const Record&) = delete;

    std::ostringstream& stream() { return buffer_; }

  private:
    Level level_;
    std::ostringstream buffer_;
};

} // namespace logging

/**
 * @brief Stream a log record at the given severity, e.g.
 *        @c HG_LOG(Info) << "Fluid profile constructed";
 *
 * Below the threshold nothing is constructed and the streamed arguments are
 * never evaluated, so it is safe to log expensive expressions.
 *
 * The loop form (rather than a bare @c if) keeps the macro safe to use as the
 * body of an unbraced @c if ... @c else.
 */
#define HG_LOG(lvl)                                                          \
    for (bool _hg_log_once = ::logging::enabled(::logging::Level::lvl);       \
         _hg_log_once; _hg_log_once = false)                                  \
        ::logging::Record(::logging::Level::lvl).stream()

#endif // INCLUDE_LOGGER_HPP_H
