/**
 * @file sici.hpp
 * @brief Fast Si/Ci functions with lookup-based interpolation and asymptotics.
 *
 * Defines constants controlling the lookup table range and provides
 * inline routines `lookup_sici` and `sici` for computing the sine and
 * cosine integral functions efficiently.
 */

#pragma once
#include <algorithm>
#include <cmath>

// Lookup arrays generated by Python script
#include "sici_arrays.hpp"
#include "specialfunctions.h"

/// Number of entries in the precomputed Si/Ci lookup tables.
constexpr int N_LOOKUP = 10000;
/// Minimum argument supported by the lookup table.
constexpr double X_MIN = -100.;
/// Maximum argument supported by the lookup table.
constexpr double X_MAX = 100.;

/**
 * @brief Interpolate Si and Ci values from precomputed lookup arrays.
 *
 * Given an argument \p x within [X_MIN, X_MAX], this routine computes
 * Si(x) and Ci(x) using cubic interpolation of arrays generated by a
 * Python pre-processing script.  For values outside the range, the
 * nearest endpoint is used as a fallback (should not occur in practice).
 *
 * @param x  Input value.
 * @param si Output reference for Si(x).
 * @param ci Output reference for Ci(x).
 */
inline void lookup_sici(double x, double& si, double& ci) {
    if (x >= X_MAX) {
        // fall back, should never hit this
        si = si_vals[N_LOOKUP - 1];
        ci = ci_vals[N_LOOKUP - 1];
        return;
    } else if (x <= X_MIN) {
        // fall back, should never hit this
        si = si_vals[0];
        ci = ci_vals[0];
        return;
    }
    
    constexpr double range_inv = 1.0 / (X_MAX - X_MIN);
    constexpr double lookup_scale = (N_LOOKUP - 1) * range_inv;
    
    const double t = (x - X_MIN) * lookup_scale;
    const int idx = static_cast<int>(t);
    
    const int i1 = std::max(1, std::min(idx, N_LOOKUP - 3));
    const int i0 = i1 - 1;
    const int i2 = i1 + 1; 
    const int i3 = i1 + 2;
    
    const double frac = t - i1;
    
    const double frac2 = frac * frac;
    const double frac3 = frac2 * frac;
    
    const double c0 = -0.5 * frac3 + frac2 - 0.5 * frac;
    const double c1 = 1.5 * frac3 - 2.5 * frac2 + 1.0;
    const double c2 = -1.5 * frac3 + 2.0 * frac2 + 0.5 * frac;
    const double c3 = 0.5 * frac3 - 0.5 * frac2;
    
    si = c0 * si_vals[i0] + c1 * si_vals[i1] + c2 * si_vals[i2] + c3 * si_vals[i3];
    ci = c0 * ci_vals[i0] + c1 * ci_vals[i1] + c2 * ci_vals[i2] + c3 * ci_vals[i3];
}

/**
 * @brief Compute the sine and cosine integrals Si(x) and Ci(x).
 *
 * This function uses asymptotic expansions for large |x| and falls
 * back to `lookup_sici` (or optionally ALGLIB) for smaller values.
 *
 * @param x  Input value.
 * @param si Output reference for Si(x).
 * @param ci Output reference for Ci(x).
 */
inline void sici(double x, double& si, double& ci) {

    constexpr double pi_2 = M_PI/2;
    const double x_abs = abs(x);
    
    // leading order
    if (x_abs >= 1000.) {
        si = (x >= 0) ? pi_2 : -pi_2;
        ci = 0.;
        return;
    }

    // first order
    if (x_abs > 500.) {
        const double inv_x = 1.0 / x;
        const double cos_x = cos(x);
        const double sin_x = sin(x);
        
        si = pi_2 - cos_x * inv_x;
        ci = sin_x * inv_x;

        if (x < 0) {
            si = -si;
        }
        return;
    }

    // second order
    if (x_abs >= 100.) {
        const double inv_x = 1.0 / x;
        const double cos_x = cos(x);
        const double sin_x = sin(x);
        
        si = pi_2 - (cos_x - sin_x * inv_x) * inv_x;
        ci = (sin_x - cos_x * inv_x) * inv_x;
        
        if (x < 0) {
            si = -si;
        }
        return;
    }

    // fall back to lookup for small x
    lookup_sici(x, si, ci);
    // alglib::sinecosineintegrals(x, si, ci);
}